services:
#    game.example:
#        class: GameBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    game.statistique.averageNote:
        class: GameBundle\Service\GameStats
        arguments:
            - '@doctrine.orm.entity_manager'